# Generated by Django 5.0.1 on 2024-03-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='description',
            new_name='Product',
        ),
    ]
