# Generated by Django 5.0.1 on 2024-03-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_description_search_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='Product',
            new_name='Products',
        ),
    ]
