# Generated by Django 5.0.1 on 2024-03-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_buyproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproduct',
            name='product_qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
